docs: add example for: awscc_ec2_prefix_list
hashicorp/terraform-provider-awscc pull request #1036
Opened 2023-06-30 16:23 UTC by catlike

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2023-06-30 19:51 UTC, wellsiau-aws commented on examples/resources/awscc_ec2_prefix_list/ec2_prefix_list_ipv4.tf
> +}
```suggestion
resource "awscc_ec2_prefix_list" "example_prefix_list" {
  address_family   = "IPv4"
  max_entries      = 5
  prefix_list_name = "example-ipv4-prefix-list"
  entries = [
    {
      cidr        = "10.10.0.0/16"
      description = "example network"
    },
    {
      cidr        = "192.168.2.8/32"
      description = "example host"
    }
  ]
}
```

2023-06-30 19:51 UTC, wellsiau-aws commented on examples/resources/awscc_ec2_prefix_list/ec2_prefix_list_ipv6.tf
> +}
```suggestion
resource "awscc_ec2_prefix_list" "example_ipv6_prefix_list" {
  address_family   = "IPv6"
  max_entries      = 5
  prefix_list_name = "example-ipv6-prefix-list"
  entries = [
    {
      cidr        = "2001:db8::/32"
      description = "example network"
    },
    {
      cidr        = "2001:db8:abcd:0012::0/128"
      description = "example host"
    }
  ]
}
```

2023-06-30 19:52 UTC, wellsiau-aws requested changes
Small minor suggestion to tidy-up the formatting, otherwise looks good. Thanks!

2023-06-30 23:41 UTC, wellsiau-aws approved these changes
LGTM, thanks!

2023-07-31 15:01 UTC, wellsiau-aws approved these changes

2023-08-03 16:55 UTC, merged

2023-08-03 16:55 UTC, marcosentino commented
@catlike Thanks for the contribution!