docs: add example for: awscc_route53_hosted_zone
hashicorp/terraform-provider-awscc pull request #1157
Opened 2023-08-18 18:36 UTC by ishwar-amzn

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2023-08-25 22:55 UTC, wellsiau-aws requested changes
please don't merge until we address the peculiarity with the `vp_cs` attribute

2023-08-25 22:55 UTC, wellsiau-aws commented on examples/resources/awscc_route53_hosted_zone/awscc_route53_hosted_zone_private.tf
> +  vp_cs = [
this part doesnt read right, lets investigate this a bit

2023-08-25 22:55 UTC, wellsiau-aws commented on examples/resources/awscc_route53_hosted_zone/awscc_route53_hosted_zone_private.tf
> +  vp_cs = [
https://github.com/hashicorp/terraform-provider-awscc/blob/2e5e4089ce02498d5dbfb40d5e2900831b284f8a/internal/aws/route53/hosted_zone_resource_gen.go#L237C4-L237C9

2023-08-25 22:55 UTC, wellsiau-aws commented on examples/resources/awscc_route53_hosted_zone/awscc_route53_hosted_zone_private.tf
> +  vp_cs = [
@ewbankkit , is there a overrides that explain why this attribute map from "VPC" into "vp_cs"

2024-04-03 14:13 UTC, merged

2024-04-03 14:13 UTC, marcosentino commented
@ishwar-amzn Thank you for the contribution!