doc_config_config_rule
hashicorp/terraform-provider-awscc pull request #1179
Opened 2023-08-29 15:31 UTC by alex-torres1980

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2023-09-11 14:48 UTC, wellsiau-aws commented on examples/resources/awscc_config_config_rule/config_config_rule.tf
> +  config_rule_name = ""
empty string for resource name is not recommended, please add some meaningful resource name

2023-09-11 14:49 UTC, wellsiau-aws commented on examples/resources/awscc_config_config_rule/config_config_rule.tf
> +resource "awscc_config_config_rule" "r" {
I would avoid ambiguous resource logical id such as `r` , can you please look at other example, at minimum you can use something like `example`

2023-09-11 15:23 UTC, wellsiau-aws requested changes
thanks for your contribution, please check couple suggestions above

2023-09-11 17:49 UTC, wellsiau-aws approved these changes
thank you for the contribution, LGTM now

2023-09-14 14:30 UTC, merged

2023-09-14 14:30 UTC, marcosentino commented
@alex-torres1980 Thank you for the contribution!