docs - personalize dataset
hashicorp/terraform-provider-awscc pull request #1343
Opened 2023-11-23 15:49 UTC by dansantf

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2023-12-15 23:06 UTC, catlike commented
LGTM 🚀

2023-12-15 23:08 UTC, catlike approved these changes
LGTM 🚀

2024-02-26 19:43 UTC, wellsiau-aws approved these changes
LGTM! thanks @dansantf

2024-04-04 03:33 UTC, wellsiau-aws requested changes
Please check the comment about file `./personalize_dataset_group.md` 
this causing a conflict and I suggest you to remove it.

2024-04-04 03:33 UTC, wellsiau-aws commented on templates/resources/personalize_dataset_group.md.tmpl
@dansantf , perhaps this is an error? I dont think we need to include this file since you are not making any changes to `awscc_personalize_dataset_group` ? 

I believe you have this completed on the previous [PR](https://github.com/hashicorp/terraform-provider-awscc/pull/1319)

2024-04-04 20:00 UTC, wellsiau-aws commented
@dansantf , dont forget to re-run `make docs`, thanks!

2024-04-12 16:07 UTC, wellsiau-aws approved these changes
LGTM, thank you!

2024-04-15 19:49 UTC, merged

2024-04-15 19:50 UTC, marcosentino commented
@dansantf Thank you for the contribution!