docs: add example for: awscc_controltower_enabled_control
hashicorp/terraform-provider-awscc pull request #1489
Opened 2024-03-22 11:29 UTC by gokendra1

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2024-03-28 02:51 UTC, wellsiau-aws commented
@Gokendra , thank you for your contribution.

instead of adding the md file directly, could you use the `.md.tmpl` template file instead

you can find example of similar pull request here: https://github.com/hashicorp/terraform-provider-awscc/pull/1343/files

2024-04-08 15:30 UTC, wellsiau-aws requested changes
minor tweak requested, please have a look

2024-04-08 15:30 UTC, wellsiau-aws commented on examples/resources/awscc_controltower_enabled_control/controltower_enabled_control.tf
> +  target_identifier  = "arn:aws:organizations::000123456789:ou/o-ydkk7uvfj1/ou-e3wm-2x760yqd"
```suggestion
  target_identifier  = "arn:aws:organizations::<<your-account-id>:ou/<<your-org-id>>/<<your-ou-id>>"
```

2024-04-08 15:30 UTC, wellsiau-aws commented on examples/resources/awscc_controltower_enabled_control/controltower_enabled_control.tf
> +# Please change the Organization ID from 'o-ydkk7uvfj1' to your Organization ID, and the Organizational Unit ID from 'u-e3wm-2x760yqd' to your desired OU where the controls need to be implemented.
```suggestion
# Please change the Organization ID to your Organization ID, and the Organizational Unit ID to your desired OU where the controls need to be implemented.
```

2024-04-08 18:06 UTC, wellsiau-aws approved these changes
LGTM

2024-04-09 13:52 UTC, merged

2024-04-09 13:52 UTC, marcosentino commented
@gokendra1 Thank you for the contribution!