docs: added examples for datazone_domain
hashicorp/terraform-provider-awscc pull request #1588
Opened 2024-04-19 05:17 UTC by quixoticmonk

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

2024-04-25 22:00 UTC, wellsiau-aws requested changes
Please take a look at the suggested change and correct my assumption as needed. Thanks!

2024-04-25 22:00 UTC, wellsiau-aws commented on examples/resources/awscc_datazone_domain/datazone_domain.tf
> +  description = "AWS account id"
```suggestion
  description = "Source AWS account id"
```

nit pick, I believe this should be called the source account id

2024-04-25 22:00 UTC, wellsiau-aws commented on examples/resources/awscc_datazone_domain/datazone_domain.tf
> +variable "account_id" {
```suggestion
variable "source_account_id" {
```

2024-04-25 22:00 UTC, wellsiau-aws commented on examples/resources/awscc_datazone_domain/datazone_domain.tf
> +            "aws:SourceAccount" : var.account_id
```suggestion
            "aws:SourceAccount" : var.source_account_id
```

2024-04-25 23:53 UTC, wellsiau-aws approved these changes
LGTM, thanks !

2024-04-26 12:54 UTC, merged

2024-04-26 12:54 UTC, marcosentino commented
@quixoticmonk Thank you for the contribution!