docs: add example for awscc_cloudtrail_trail
hashicorp/terraform-provider-awscc pull request #1604
Opened 2024-04-22 21:38 UTC by BondAnthony

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2024-04-22 22:11 UTC, quixoticmonk approved these changes

2024-04-26 02:01 UTC, wellsiau-aws requested changes
Please have a look at the minor suggestion, otherwise looks good!

2024-04-26 02:01 UTC, wellsiau-aws commented on examples/resources/awscc_cloudtrail_trail/complex_trail.tf
> +      }
```suggestion
      {
        field  = "resources.type"
        equals = ["AWS::S3::Object"]
      },
      {
        field  = "resources.ARN"
        equals = ["arn:aws:s3:::my-target-bucket/"]
      }
```

I suggest we scope this down to limit potential unintended cost overruns

2024-04-26 12:46 UTC, merged

2024-04-26 13:17 UTC, BondAnthony commented on docs/resources/cloudtrail_trail.md
> +        equals = ["AWS::S3::Object"]
That's a good point. I'll provide an updated example.

2024-04-26 16:15 UTC, BondAnthony commented on docs/resources/cloudtrail_trail.md
> +        equals = ["AWS::S3::Object"]
PR with the updated example. https://github.com/hashicorp/terraform-provider-awscc/pull/1619