docs: added examples for awscc_signer_signing_profile
hashicorp/terraform-provider-awscc pull request #1674
Opened 2024-05-03 03:16 UTC by quixoticmonk

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

There is a deployment issue when tags are added to the resource which is called out in #1673

2024-05-12 19:04 UTC, wellsiau-aws commented on templates/resources/signer_signing_profile.md.tmpl
> +{{ tffile (printf "examples/resources/%s/signer_signing_profile_validity.tf" .Name)}}
```suggestion
{{ tffile (printf "examples/resources/%s/signer_signing_profile.tf" .Name)}}
```

I believe this one should be the example without validity period

2024-05-12 19:04 UTC, wellsiau-aws requested changes
@quixoticmonk please take a look at the suggested changes, thanks!

2024-05-12 22:29 UTC, quixoticmonk commented
> @quixoticmonk please take a look at the suggested changes, thanks!

Updated.

2024-05-14 05:00 UTC, wellsiau-aws approved these changes
LGTM, thank you!

2024-05-14 13:44 UTC, merged

2024-05-14 13:44 UTC, marcosentino commented
@quixoticmonk Thank you for the contribution!