docs: added example for awscc_verifiedpermissions_policy_store
hashicorp/terraform-provider-awscc pull request #1676
Opened 2024-05-03 04:03 UTC by quixoticmonk

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

2024-05-12 18:57 UTC, wellsiau-aws commented on examples/resources/awscc_verifiedpermissions_policy_store/verifiedpermissions_policy_store.tf
> +    cedar_json = jsonencode({ "PhotoApp" : { "commonTypes" : { "PersonType" : { "type" : "Record", "attributes" : { "age" : { "type" : "Long" }, "name" : { "type" : "String" } } }, "ContextType" : {
```suggestion
    cedar_json = jsonencode({
      "PhotoApp": {
        "commonTypes": {
          "PersonType": {
            "type": "Record",
            "attributes": {
              "age": {
                "type": "Long"
              },
              "name": {
                "type": "String"
              }
            }
          },
          "ContextType": {
            "type": "Record",
            "attributes": {
              "ip": {
                "type": "Extension",
                "name": "ipaddr",
                "required": false
              },
              "authenticated": {
                "type": "Boolean",
                "required": true
              }
            }
          }
        },
        "entityTypes": {
          "User": {
            "shape": {
              "type": "Record",
              "attributes": {
                "userId": {
                  "type": "String"
                },
                "personInformation": {
                  "type": "PersonType"
                }
              }
            },
            "memberOfTypes": [
              "UserGroup"
            ]
          },
          "UserGroup": {
            "shape": {
              "type": "Record",
              "attributes": {}
            }
          },
          "Photo": {
            "shape": {
              "type": "Record",
              "attributes": {
                "account": {
                  "type": "Entity",
                  "name": "Account",
                  "required": true
                },
                "private": {
                  "type": "Boolean",
                  "required": true
                }
              }
            },
            "memberOfTypes": [
              "Album",
              "Account"
            ]
          },
          "Album": {
            "shape": {
              "type": "Record",
              "attributes": {}
            }
          },
          "Account": {
            "shape": {
              "type": "Record",
              "attributes": {}
            }
          }
        },
        "actions": {
          "viewPhoto": {
            "appliesTo": {
              "principalTypes": [
                "User",
                "UserGroup"
              ],
              "resourceTypes": [
                "Photo"
              ],
              "context": {
                "type": "ContextType"
              }
            }
          },
          "createPhoto": {
            "appliesTo": {
              "principalTypes": [
                "User",
                "UserGroup"
              ],
              "resourceTypes": [
                "Photo"
              ],
              "context": {
                "type": "ContextType"
              }
            }
          },
          "listPhotos": {
            "appliesTo": {
              "principalTypes": [
                "User",
                "UserGroup"
              ],
              "resourceTypes": [
                "Photo"
              ],
              "context": {
                "type": "ContextType"
              }
            }
          }
        }
      }
    })
```

2024-05-12 18:57 UTC, wellsiau-aws commented on examples/resources/awscc_verifiedpermissions_policy_store/verifiedpermissions_policy_store.tf
> +    cedar_json = jsonencode({ "PhotoApp" : { "commonTypes" : { "PersonType" : { "type" : "Record", "attributes" : { "age" : { "type" : "Long" }, "name" : { "type" : "String" } } }, "ContextType" : {
beautify the json schema for readability

2024-05-12 18:57 UTC, wellsiau-aws requested changes
@quixoticmonk , small nit about the schema, please take a look, thanks !

2024-05-14 01:13 UTC, quixoticmonk commented
> @quixoticmonk , small nit about the schema, please take a look, thanks !

Took care of the changes. Merged the changes from latest merge into main as well.

2024-05-14 05:01 UTC, wellsiau-aws approved these changes
LGTM, thank you!

2024-05-14 13:43 UTC, merged

2024-05-14 13:44 UTC, marcosentino commented
@quixoticmonk Thank you for the contribution!