docs: added examples for awscc_qbusiness_web_experience
hashicorp/terraform-provider-awscc pull request #1707
Opened 2024-05-15 01:40 UTC by quixoticmonk

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

2024-05-17 19:47 UTC, BondAnthony approved these changes
Thank you!

2024-05-27 23:05 UTC, wellsiau-aws commented on examples/resources/awscc_qbusiness_web_experience/qbusiness_web_experience.tf
> +
```suggestion
  policies = [{
    policy_name = "qbusiness_policy"
    policy_document = jsonencode({
      Version = "2012-10-17"
      Statement = [
        {
          Sid = "QBusinessConversationPermission"
          Effect = "Allow"
          Action = [
            "qbusiness:Chat",
            "qbusiness:ChatSync",
            "qbusiness:ListMessages",
            "qbusiness:ListConversations",
            "qbusiness:DeleteConversation",
            "qbusiness:PutFeedback",
            "qbusiness:GetWebExperience",
            "qbusiness:GetApplication",
            "qbusiness:ListPlugins",
            "qbusiness:GetChatControlsConfiguration"
          ]
          Resource = awscc_qbusiness_application.example.application_arn
        }
      ]
    })
```

missing policies for the IAM role

2024-05-27 23:06 UTC, wellsiau-aws commented on examples/resources/awscc_qbusiness_web_experience/qbusiness_web_experience.tf
> +            "aws:SourceArn" = "arn:${data.aws_partition.current.id}:qbusiness:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}}:application/*"
```suggestion
            "aws:SourceArn" = awscc_qbusiness_application.example.application_arn
```

I noticed that we can scope it down further to the exact ARN

2024-05-27 23:07 UTC, wellsiau-aws requested changes
please check the suggested changes

2024-05-27 23:43 UTC, wellsiau-aws approved these changes

2024-05-27 23:43 UTC, quixoticmonk commented
> please check the suggested changes
Updated the suggested changes.

2024-05-28 02:28 UTC, merged

2024-05-28 02:28 UTC, marcosentino commented
@quixoticmonk Thank you for the contribution!