docs: added example for awscc_neptune_db_cluster
hashicorp/terraform-provider-awscc pull request #1736
Opened 2024-05-22 03:57 UTC by quixoticmonk

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Blocked by #1735

2024-06-30 17:07 UTC, wellsiau-aws requested changes
just a minor update requested, thank you!

2024-06-30 17:07 UTC, wellsiau-aws commented on examples/resources/awscc_neptune_db_cluster/neptune_db_cluster.tf
> +  kms_key_id                     = awscc_kms_key.example.key_id
```suggestion
  kms_key_id                     = awscc_kms_key.example.arn
```

I suggest to use arn to address issue reported at #1735

2024-06-30 18:51 UTC, wellsiau-aws approved these changes
LGTM

2024-07-08 16:19 UTC, merged

2024-07-08 16:19 UTC, marcosentino commented
@quixoticmonk Thank you for the contribution!