Docs - awscc_opensearchserverless_collection
hashicorp/terraform-provider-awscc pull request #927
Opened 2023-05-01 22:13 UTC by troyparrett

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2023-05-02 00:07 UTC, wellsiau-aws requested changes

2023-05-02 00:07 UTC, wellsiau-aws commented on examples/resources/awscc_opensearchserverless_collection/simple_collection.tf
> +    policy = "{\"Rules\":[{\"ResourceType\":\"collection\",\"Resource\":[\"collection/awscc-collection\"]}],\"AWSOwnedKey\":true}"
```suggestion
  policy = jsonencode({
    Rules = [
      {
        ResourceType = "collection",
        Resource     = "collection/awscc-collection"
      }
    ],
    AWSOwnedKey = true
  })
```

2023-05-02 00:07 UTC, wellsiau-aws commented on examples/resources/awscc_opensearchserverless_collection/simple_collection.tf
> +    policy = "{\"Rules\":[{\"ResourceType\":\"collection\",\"Resource\":[\"collection/awscc-collection\"]}],\"AWSOwnedKey\":true}"
use `jsonencode` to make the policy readable

2023-05-02 21:15 UTC, troyparrett commented
@wellsiau-aws - made the changes, good suggestion

2023-05-03 03:58 UTC, wellsiau-aws requested changes
very minor nit-pick about the identation

2023-05-03 03:58 UTC, wellsiau-aws commented on examples/resources/awscc_opensearchserverless_collection/simple_collection.tf
> +  policy = jsonencode({
careful with the indent here, its always a good practice to run `terraform fmt` on your local repo

2023-05-03 11:12 UTC, troyparrett commented
done!

2023-05-03 14:56 UTC, wellsiau-aws approved these changes
LGTM, thanks!

2023-05-03 19:27 UTC, merged

2023-05-03 19:27 UTC, breathingdust commented
LGTM 🚀 , thanks for the contribution @troyparrett!