docs - awscc_ecr_repository
hashicorp/terraform-provider-awscc pull request #930
Opened 2023-05-04 23:13 UTC by jackywong-amazon

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #469

2023-05-05 00:40 UTC, wellsiau-aws requested changes

2023-05-05 00:40 UTC, wellsiau-aws commented on examples/resources/awscc_ecr_repository/ecr_repository_lifecycle_policy.tf
> +        {
for consistency, let's keep the indentation to 2 spaces instead of 4

2023-05-05 00:40 UTC, wellsiau-aws commented on templates/resources/ecr_repository.md.tmpl
> +### ECR Repository
provide different sub-section title
i.e. ECR Repository w/ lifecycle policy

2023-05-05 00:40 UTC, wellsiau-aws commented on templates/resources/ecr_repository.md.tmpl
> +### ECR Repository
same here, provide different sub-section title

2023-05-05 15:49 UTC, wellsiau-aws approved these changes
LGTM

2023-05-05 15:56 UTC, jackywong-amazon commented on templates/resources/ecr_repository.md.tmpl
> +### ECR Repository
updated based on recommendation

2023-05-11 17:35 UTC, ewbankkit commented
@jackywong-amazon Thanks for the contribution :tada: :clap:.

2023-05-11 17:40 UTC, merged