docs - awscc_iam_role
hashicorp/terraform-provider-awscc pull request #958
Opened 2023-05-22 07:42 UTC by naveen-amzn

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

2023-05-22 12:37 UTC, rahul-amzn commented on examples/resources/awscc_iam_role/iam_role_with_inline.tf
> +data "aws_iam_policy_document" "instance_aeessume_role_policy" {
seems typo - instance_aeessume_role_policy ?

2023-05-22 12:37 UTC, rahul-amzn commented on docs/resources/iam_role.md
> +  tags = [{
@naveen-amzn may add  

```
  tags = [{
    key   = "Modified By"
    value = "AWSCC"
  }]
```

2023-05-22 12:37 UTC, rahul-amzn commented on docs/resources/iam_role.md
> +    sid       = "tes2t"
typo tes2t ?

2023-05-22 12:37 UTC, rahul-amzn commented on docs/resources/iam_role.md
> +  tags = [{
same comment for tags (everywhere)

2023-05-22 15:45 UTC, naveen-amzn commented on examples/resources/awscc_iam_role/iam_role_with_inline.tf
> +data "aws_iam_policy_document" "instance_aeessume_role_policy" {
Fixed typo.

2023-05-31 00:35 UTC, wellsiau-aws requested changes

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_managed.tf
> +    key   = "NAME"
```suggestion
    key   = "Name"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_inline.tf
> +    key   = "NAME"
```suggestion
    key   = "Name"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_assume_role.tf
> +    key   = "NAME"
```suggestion
    key   = "Name"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role.tf
> +    key   = "NAME"
```suggestion
    key   = "Name"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role.tf
> +    value = "Sample-IAM-Role"
```suggestion
    value = "Sample IAM Role"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role.tf
> +      value = "development"
```suggestion
      value = "Development"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_assume_role.tf
> +      value = "development"
```suggestion
      value = "Development"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_inline.tf
> +      value = "development"
```suggestion
      value = "Development"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_managed.tf
> +      value = "development"
```suggestion
      value = "Development"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_permission_boundry.tf
> +    key   = "NAME"
```suggestion
    key   = "Name"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_permission_boundry.tf
> +      value = "development"
```suggestion
      value = "Development"
```

2023-05-31 00:35 UTC, wellsiau-aws commented on examples/resources/awscc_iam_role/iam_role_with_permission_boundry.tf
> +resource "aws_iam_policy" "s3_permission_boundry_policy" {
typo for boundary, please check across all resources

2023-05-31 19:56 UTC, wellsiau-aws approved these changes
LGTM

2023-06-01 13:03 UTC, ewbankkit commented
@naveen-amzn Thanks for the contribution :tada: :clap:.

2023-06-01 13:03 UTC, merged